---
- name: Copy rustup-init.sh
  become: true
  become_user: isucon
  copy:
    src: rustup-init.sh
    dest: /home/isucon/local/rustup-init.sh
    mode: 0755

- name: Install Rust
  become: true
  become_user: isucon
  shell:
    cmd: /usr/bin/sh -x /home/isucon/local/rustup-init.sh -y --no-modify-path --profile default --default-toolchain 1.74.0 -c rustfmt
    chdir: /home/isucon

- name: mkdir opt/xbuild/var
  become: true
  file:
    state: directory
    path: /opt/xbuild/var
    mode: 0777
    owner: root
    group: root

- name: mkdir opt/xbuild/bin
  become: true
  file:
    state: directory
    path: /opt/xbuild/bin
    mode: 0777
    owner: root
    group: root

- name: Install Node.js
  become: true
  become_user: isucon
  shell:
    cmd: /opt/xbuild/node-install v20.10.0 /home/isucon/local/node

- name: Install Ruby
  become: true
  become_user: isucon
  shell:
    cmd: MAKE_OPTS=-j$(nproc) /opt/xbuild/ruby-install 3.2.2 /home/isucon/local/ruby

- name: Install Python
  become: true
  become_user: isucon
  shell:
    cmd: /opt/xbuild/python-install 3.12.0 /home/isucon/local/python